# Generated by Django 5.2.9 on 2025-12-08 22:20

import django.core.validators
import django.db.models.deletion
import habits.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habits",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=255, verbose_name="Место")),
                ("time", models.TimeField(verbose_name="Время")),
                ("action", models.CharField(max_length=500, verbose_name="Действие")),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Признак полезной привычки")),
                (
                    "period",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Ежедневно"),
                            (2, "Раз в два дня"),
                            (3, "Раз в три дня"),
                            (4, "Раз в четыре дня"),
                            (5, "Раз в пять дней"),
                            (6, "Раз в шесть дней"),
                            (7, "Еженедельно"),
                        ],
                        default=1,
                        validators=[habits.validators.validate_period],
                        verbose_name="Периодичность",
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=100, null=True, verbose_name="Вознаграждение")),
                (
                    "execution_time",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(120),
                            habits.validators.validate_execution_time,
                        ],
                        verbose_name="Время на выполнение",
                    ),
                ),
                ("is_published", models.BooleanField(default=True, verbose_name="Признак публичности")),
                (
                    "related_wont",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habits",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["time"],
            },
        ),
    ]
