# Generated by Django 5.2.9 on 2025-12-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habits",
            old_name="related_wont",
            new_name="related_habit",
        ),
    ]
